//----------------------------------------------------BOOKS-------------------------------------------------------------
### Get 5 random books
GET http://localhost:3000/random-books


### Get all books
GET http://localhost:3000/books

### Get one book by id
GET http://localhost:3000/book/36



//----------------------------------------------------ADMIN-------------------------------------------------------------
### Add a book in database 
POST http://localhost:3000/admin/book
Content-Type: application/json

{
    "isbn": 2848014115,
    "title": "Test ajout livre 3 - Toto l'école est finie",
    "author": "Serge Bloch",
    "summary": "Roi de la cour de récré, maître en l'art du zéro pointé, tout le monde connaît Toto ! Comment s'occupe Toto sur la route des vacances ? A quoi Toto reconnaît-il un motard heureux ? Impossible à deviner sans lire ces gags hilarants de Toto et sa bande de rigolos ! Une BD à se tordre de rire !",
    "image": "https://m.media-amazon.com/images/I/71DwQ+i0w0L._AC_UF1000,1000_QL80_.jpg",
    "pages": 111,
    "editor": "Tourbillon",
    "publication_year": 2009
}


###Edit a book in database 
PATCH http://localhost:3000/admin/book/36
Content-Type: application/json

{
    "title": "Test modification - Toto l'école est finie",
    "pages": 125,
    "editor": "Tourbillon2"
}


###Delete a book in database 
DELETE http://localhost:3000/admin/book/37




//----------------------------------------------------LIBRARY-------------------------------------------------------------
###Add a book in a library 
POST http://localhost:3000/library/1/book/27


###Edit status of a book in a library 
PATCH http://localhost:3000/library/1/book/34


###Delete a book in a library 
DELETE http://localhost:3000/library/1/book/34



//----------------------------------------------------AUTHENTIFICATION-------------------------------------------------------------
###Create user 
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Wayne",
    "firstname": "Bruce",
    "email": "test@gmail.com",
    "password": "test"
}